starting run 1 at: Sun Nov 26 14:02:41 PST 2023
python3: can't open file './src/run_redistribution.py': [Errno 2] No such file or directory
Finished at: Sun Nov 26 14:02:44 PST 2023
